### ISSUE TITLE
Setup guide for inav mate 405SE FC

### ISSUE THREAD

**Issue by jackooooo** [zosko/iNavTelemetry#2]
**Please describe feature.**
Any guide for setting it up with a FC and INAV? Ive got a DSD TECH HM-11 and I can connect to it with the app ok but get no data coming up on the screen. INAV 3. bluetooth module in on UART 1,MSP ON, 9600 Baud. Same setup works with Speedy Bee app but I just want the telemetry screen to check sats and status.

**Comment by zosko** [comment]
@jackooooo application works currently on S.Port Telemetry, MSP protocol if you are interested on it, i will put in features next thing will be that.

**Comment by jackooooo** [comment]
Thanks. MSP would be great. Btw could you use your app like in this video: 
https://m.youtube.com/watch?v=lmSMt6JLWL8
they use a android app here: https://github.com/CrazyDude1994/android-taranis-smartport-telemetry
Be nice to have a iOS app option

**Comment by zosko** [comment]
That android app support more protocols, iNav Telemetry only support S.Port for now. but at the and working the same

**Comment by zosko** [comment]
@jackooooo download new version from AppStore 1.1.0 that support MSP, i did not tested on iPhone because i dont have currently setup, i have only tested via USB on MacOS version of iNav Telemetry. Open new thread on issues to continue discussion about version is it working good MSPv2 on iOS devices.
